type: position_controllers/JointPositionController
joint: base_to_right_front_steer

/gazebo_ros_control:
  pid_gains:
      base_to_right_front_steer:
        p: 3001
        i: 20
        d: 150
        i_clamp_min: -500
        i_clamp_max: 500
