fs:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    diff_drive:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: 'JointBaseWheelBL'
      right_wheel: 'JointBaseWheelBR'
      publish_rate: 50.0               # default: 50
      pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
      twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]

      # Wheel separation and diameter. These are both optional.
      # diff_drive_controller will attempt to read either one or both from the
      # URDF if not specified as a parameter
      wheel_separation: 0.227
      wheel_radius: 0.045

      # Wheel separation and radius multipliers
      wheel_separation_multiplier: 1.0 # default: 1.0
      wheel_radius_multiplier: 1.0 # default: 1.0

      # Velocity commands timeout [s], default 0.5
      cmd_vel_timeout: 0.25

      # Base frame_id
      base_frame_id: "base_link"

      # Velocity and acceleration limits
      # Whenever a min_* is unspecified, default to -max_*
      linear:
        x:
          has_velocity_limits: false
          max_velocity: 0.10  # m/s
          min_velocity: -0.10 # m/s
          has_acceleration_limits: false
          max_acceleration: 0.025  # m/s^2
          min_acceleration: -0.025 # m/s^2
          has_jerk_limits: false
          max_jerk: 2.0  # m/s^3
      angular:
        z:
          has_velocity_limits: false
          max_velocity: 1.0472  # rad/s
          has_acceleration_limits: false
          max_acceleration: 0.5  # rad/s^2
          has_jerk_limits: false
          max_jerk: 1 # rad/s^3


    position:
      JointSteerRight:
        type: position_controllers/JointPositionController
        joint: JointSteerRight


    velocity:
      JointBaseWheelBR:
        type: velocity_controllers/JointVelocityController
        joint: JointBaseWheelBR


      JointBaseWheelBL:
        type: velocity_controllers/JointVelocityController
        joint: JointBaseWheelBL



